# -*- coding: utf-8 -*-
"""factorial.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1mGfYNu48ZPvb7fcRmJT5SdRqwL0v8j
"""

# Factorial of a number

num = int(input("Enter a number: "))

factorial = 1

if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    for i in range(1, num + 1):
        factorial = factorial * i

    print("Factorial of", num, "is", factorial)